Added integrations tutorial
Achiefs/documentation.achiefs.github.io pull request #6
Opened 2023-08-03 14:49 UTC by okynos

Hello!

Coming from #5 we have added integrations tutorial to configure FIM with network environment.

This PR closes #5 
Added:
- Splunk integration tutorial with images.
- ElasticSearch/OpenSearch tutorial.
- Added `token` parameter in configuration page.
- Added `max_file_checksum` parameter.
- Added `watcher` selector parameter.

Regards!

2023-08-03 15:19 UTC, Zenidd commented on docs/integrations.md
> +![Splunk home page](../../assets/images/splunk/home.png)
Screenshots are broken both in my local copy of the repo and on the online preview @okynos 
![image](https://github.com/Achiefs/documentation.achiefs.github.io/assets/14923294/3f5e7696-7862-4fb5-ac4c-00f49e8de4bc)

2023-08-03 15:19 UTC, Zenidd requested changes
Please fix the broken screenshots

2023-08-04 09:20 UTC, okynos commented
Solved in https://github.com/Achiefs/documentation.achiefs.github.io/pull/6/commits/b03b4f7ab84419c4793b8e5ed2cb3057f6ac6c56
and https://github.com/Achiefs/documentation.achiefs.github.io/pull/6/commits/10160071eb4afb5fce88098af30fb6f149e9688f

The images works as expected in development environment. Unfortunately Jekyll works this way.
![image](https://github.com/Achiefs/documentation.achiefs.github.io/assets/10661307/468a90bd-5361-493b-9936-c6774231754d)

2023-08-04 09:25 UTC, Zenidd commented
> The images work as expected in development environment. Unfortunately Jekyll works this way.


I see! Was expecting the .png file to be rendered in the MD in the local/Github preview. 

LGTM!

2023-08-04 09:29 UTC, merged